"""The content schema of a world (PHASE1_CONTRACTS D.E): what an editor needs to build forms.

JSON Schema for rooms, features, entities, items and zones, the extension fields every enabled
plugin claims on them (``room.shop``, ``item.slot`` ...), and the world's own lists: room types,
exit directions, equipment slots, attributes, vitals and currencies. Served by
``GET /schema/world`` and written by ``python -m sage schema export``; each world package keeps
an exported copy at ``content.schema.json`` for offline editors (a test keeps it current).
"""

from __future__ import annotations

import json
from typing import Any

from sage.world.models import EntityTemplate, FeatureModel, ItemTemplate, RoomModel, ZoneModel

SCHEMA_FILE = "content.schema.json"
SCHEMA_VERSION = 1


def content_schema(world: Any, extensions: Any) -> dict[str, Any]:
    manifest = world.manifest
    return {
        "$comment": (
            f"Generated by `python -m sage schema export --world {world.id} --out "
            f"worlds/{world.id}/{SCHEMA_FILE}`; do not edit."
        ),
        "schema_version": SCHEMA_VERSION,
        "world": {"id": world.id, "name": manifest.world.name, "version": manifest.world.version},
        "content": {
            "room_types": list(manifest.content.room_types),
            "exit_dirs": list(manifest.content.exit_dirs),
            "equipment_slots": list(manifest.content.equipment_slots),
        },
        "attributes": [a.model_dump() for a in world.stats.attributes],
        "vitals": [v.model_dump() for v in world.stats.vitals],
        "currencies": [c.model_dump() for c in world.currencies],
        "models": {
            "room": RoomModel.model_json_schema(),
            "feature": FeatureModel.model_json_schema(),
            "entity": EntityTemplate.model_json_schema(),
            "item": ItemTemplate.model_json_schema(),
            "zone": ZoneModel.model_json_schema(),
        },
        "extensions": extensions.schemas(),
    }


def dumps(schema: dict[str, Any]) -> str:
    """Stable text form (sorted keys, trailing newline) so the exported file diffs cleanly."""
    return json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
