"""SQLAlchemy ORM models — Account, Character, AdminStaff, AccountSceneImage."""

from datetime import datetime
from typing import Any

from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, Index, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from sage.state.postgres import Base
from sage.state.state_types import CharacterStats, InventoryItem


def default_character_stats() -> CharacterStats:
    """Empty: attributes and vitals come from the running world's stats.yaml at creation."""
    return {}


class Account(Base):
    """Player account credentials and metadata."""

    __tablename__ = "accounts"

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(50), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    email: Mapped[str | None] = mapped_column(String(255))
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    last_login: Mapped[datetime | None] = mapped_column(DateTime)
    # Spendable balance for AI art (portraits / scene art); display label from comfyui.currency_display_name.
    ai_credits: Mapped[int] = mapped_column(Integer, default=0)
    # In-game GM crown / staff-visible play account (separate from admin_staff console logins).
    is_gm: Mapped[bool] = mapped_column(Boolean, default=False)
    # Set by staff (migration s2t3u4v5w6x7): a suspended account cannot sign in or use a play token.
    suspended_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    suspended_reason: Mapped[str | None] = mapped_column(String(500), nullable=True)
    # A muted account's characters cannot say, emote or tell until muted_until.
    muted_until: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    mute_reason: Mapped[str | None] = mapped_column(String(500), nullable=True)

    # Relationships
    characters: Mapped[list["Character"]] = relationship(
        back_populates="account", cascade="all, delete-orphan"
    )
    scene_images: Mapped[list["AccountSceneImage"]] = relationship(
        back_populates="account", cascade="all, delete-orphan"
    )


class AccountSceneImage(Base):
    """Per-account history of ComfyUI scene images (player gallery)."""

    __tablename__ = "account_scene_images"

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("accounts.id", ondelete="CASCADE"), index=True
    )
    image_url: Mapped[str] = mapped_column(String(2048))
    character_id: Mapped[int | None] = mapped_column(
        ForeignKey("characters.id", ondelete="SET NULL"), nullable=True
    )
    prompt_preview: Mapped[str | None] = mapped_column(String(512), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    account: Mapped["Account"] = relationship(back_populates="scene_images")


class Character(Base):
    """Persistent game character data linked to an account."""

    __tablename__ = "characters"

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(ForeignKey("accounts.id"))
    name: Mapped[str] = mapped_column(String(50), unique=True, index=True)

    # Portrait: URL served under Nexus /media/portraits/... when generated locally; optional.
    portrait_url: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    portrait_prompt: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Last ComfyUI scene image this character paid for; served under /media/rooms/ or /media/room-art/.
    last_scene_image_url: Mapped[str | None] = mapped_column(String(2048), nullable=True)

    # World state
    # Always set explicitly: new characters start in the world's start room (world.toml).
    room_id: Mapped[str] = mapped_column(String(255))
    # Opt-in player vs player; default off until toggled in-game or by admin.
    pvp_enabled: Mapped[bool] = mapped_column(Boolean, default=False)

    # JSONB (migration o8p9q0r1s2t3): shapes documented by state_types.CharacterStats /
    # InventoryItem. Top-level stats keys are engine vitals, world attributes and plugin blocks.
    stats: Mapped[CharacterStats] = mapped_column(JSONB, default=default_character_stats)

    inventory: Mapped[list[InventoryItem]] = mapped_column(JSONB, default=list)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    # Relationships
    account: Mapped["Account"] = relationship(back_populates="characters")


# Character names are unique regardless of case (migration l5m6n7o8p9q0). Declared here so
# autogenerate sees it; without this, the next autogenerated migration would drop the index.
Index("ix_characters_name_lower", func.lower(Character.name), unique=True)


class AdminStaff(Base):
    """Console staff (head admin, admin, GM) with optional tool/zone restrictions."""

    __tablename__ = "admin_staff"

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    display_name: Mapped[str] = mapped_column(String(120), default="")
    # head_admin | admin | gm
    role: Mapped[str] = mapped_column(String(32), default="gm")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    # {"tools": ["dashboard", "players", ...], "zones": ["*"] | ["zone_id", ...]}
    permissions: Mapped[dict[str, Any]] = mapped_column(JSON, default=lambda: {})
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )


class WorldOverride(Base):
    """Versioned live edits to world assets made from Nexus (contracts B.7).

    One row per saved version. At most one version per (kind, key) is active; rolling back
    re-activates an older row. The world package files stay the defaults underneath.
    """

    __tablename__ = "world_overrides"
    __table_args__ = (Index("ix_world_overrides_kind_key", "kind", "key"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    kind: Mapped[str] = mapped_column(String(32))  # lexicon (prompt, style, param later)
    key: Mapped[str] = mapped_column(String(255))
    version: Mapped[int] = mapped_column(Integer)
    value: Mapped[Any] = mapped_column(JSON)
    active: Mapped[bool] = mapped_column(Boolean, default=False)
    author_staff_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class AdminAuditLog(Base):
    """One staff action in the admin console: who, what, on which target, with details."""

    __tablename__ = "admin_audit_log"

    id: Mapped[int] = mapped_column(primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, index=True)
    staff_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    staff_username: Mapped[str] = mapped_column(String(64))
    action: Mapped[str] = mapped_column(String(64), index=True)
    target: Mapped[str] = mapped_column(String(255))
    detail: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict)


class CharacterSnapshot(Base):
    """A character's room, stats and inventory as they were, taken before a staff change.

    Staff can put a character back to any snapshot. The newest few per character are kept.
    """

    __tablename__ = "character_snapshots"

    id: Mapped[int] = mapped_column(primary_key=True)
    character_id: Mapped[int] = mapped_column(
        ForeignKey("characters.id", ondelete="CASCADE"), index=True
    )
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    staff_username: Mapped[str] = mapped_column(String(64))
    reason: Mapped[str] = mapped_column(String(64))
    room_id: Mapped[str] = mapped_column(String(255))
    stats: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict)
    inventory: Mapped[list[Any]] = mapped_column(JSONB, default=list)


class AccountLogin(Base):
    """One sign-in. ``address`` is kept only while the operator records sign-in addresses."""

    __tablename__ = "account_logins"

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("accounts.id", ondelete="CASCADE"), index=True
    )
    at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, index=True)
    method: Mapped[str] = mapped_column(String(16))
    address: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)


class AddressBan(Base):
    """A network address or range (CIDR) refused at sign-in, registration and play."""

    __tablename__ = "address_bans"

    id: Mapped[int] = mapped_column(primary_key=True)
    network: Mapped[str] = mapped_column(String(64), unique=True)
    reason: Mapped[str] = mapped_column(String(500), default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    created_by: Mapped[str] = mapped_column(String(64))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)


class PlayerReport(Base):
    """A bug, typo, idea or player complaint sent with the in-game report command."""

    __tablename__ = "player_reports"

    id: Mapped[int] = mapped_column(primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, index=True)
    account_id: Mapped[int | None] = mapped_column(
        ForeignKey("accounts.id", ondelete="SET NULL"), nullable=True
    )
    character_name: Mapped[str] = mapped_column(String(50))
    room_id: Mapped[str] = mapped_column(String(255), default="")
    text: Mapped[str] = mapped_column(String(2000))
    status: Mapped[str] = mapped_column(String(16), default="open", index=True)
    staff_note: Mapped[str | None] = mapped_column(String(2000), nullable=True)
    handled_by: Mapped[str | None] = mapped_column(String(64), nullable=True)
    handled_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
